USE dbProjetE2Test
GO
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Abeilles');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Abstrait');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Adaptation littéraire','Une adaptation d''un roman sous format vidéoludique');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Affrontement guerrier','Un jeu qui tourne autour des combats, gladiateur, guerre, etc');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Afrique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Allemagne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Alpinisme');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Amérique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Angleterre');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Animaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Animaux champêtres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Animaux domestiques');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Animaux exotiques');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Animaux insectes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Animaux marins');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Anniversaire');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Antiquité');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Araignées');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Archéologie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Architecture');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Argentine');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Art');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Arts martiaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Asie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Atlantide');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Australie');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Automobile','Un jeu où pratiquement  tout tourne autour des voiture');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Autriche');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Avion');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Avions','Je ne comprend pas ces quoi la diffèrence avec l''autre');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Ânes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Baleines');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Banquise');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Bar');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Base spatiale');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Belgique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Bergers');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Billard','Pour les jeu qui ne comporte que du billard, pas comme un mini-jeux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Boissons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Brocante');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cache-Cache');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cadeaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Café');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cambriolage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Camions');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Camping');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Canards');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Caractère');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Caraïbes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Casino');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chameaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Charbon');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chasse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chasse au trésor');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chats');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Château');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chevalerie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chevaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chèvres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chiens');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chine');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Chocolat');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cinéma');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cirque');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Clowns');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Coccinelles');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cochons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Colonisation');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Commerce');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Confrontation');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Conquête de l''Ouest');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Conte');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Contes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Corps humain');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Corse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Costumes / Déguisements');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Couleurs');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Course');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cowboys');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cowboys / Indiens');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Crabes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Crevettes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Crocodiles');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cuisine');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Cuisine / Boisson');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Culture / Agriculture');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Culture générale');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Danse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Dessin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Défis');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Dérive des continents');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Désert');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Développement');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Diable');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Diamants');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Dinosaures');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Dragons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Duel');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Eau');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Egypte');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Enfants');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Enquête');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Aquatique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Banquise');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Château');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Décharge publique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Désert');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement étang');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Ferme');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Grotte');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Hotel / Restaurant / Café');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Île');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Jardin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Jungle / Forêt');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Monastère');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Montagne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Sous-Marin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Ville');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Volcan');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Environnement Zoo');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Escalade');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Escrime');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Espace');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Espagne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Espionnage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Europe');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Exploration');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Extra-terrestres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Écologie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Écosse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Écureuils');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Élevage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Éléphants');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Énergie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Époque victorienne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Étang');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Évasion');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Famille');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fantastique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fantômes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Ferme');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Feu d''artifice');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fête');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Filles / Garçons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fleurs');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Football');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Forêt');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Formes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Formule 1');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fouille');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fourmis');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('France');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fromage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fruits / Légumes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Fusées');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Gendarmes / Voleurs');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Géographie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Girafes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Grenouilles');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Grêce');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Grotte');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Guerre Mondiale');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Heroic-fantaisy');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire Antiquité');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire biblique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire Guerre Mondiale');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire Médiévale');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire Renaissance');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Histoire Sixties');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Horreur');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Hotel / Restaurant / Café');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Improvisation');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Industrie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Informatique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Insectes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Invention');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Italie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Île');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Japon');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Jardin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Jeux de cirque');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Jeux vidéo');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Joaillerie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Jungle / Forêt');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Kermesse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Killer');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Labyinthe');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Labyrinthe');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lapins');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Légende');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Afrique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Allemagne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Amérique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Amérique du Sud');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Angleterre');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Asie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Australie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Autriche');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Belgique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Caraïbes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Caraïbes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Ecosse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Espagne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Europe');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu France');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Grêce');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Italie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Méditérranée');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Monde');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Pacifique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Proche-Orient');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lieu Suisse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Linguistique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Livre');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Loups');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Lune');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mafia');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Magie / Sorcellerie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Maison');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Marché / Bourse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mer');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Merveilles du monde');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Médecine');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Méditérranée');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mille et une nuits');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mine');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Monastère');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Monde');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Monstres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Montagne');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Montgolfières');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Moto');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mots / Lettres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mouches');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Moutons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Moyen-age');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Musique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Musique / Chansons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Mythologie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Napoléon');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Nature');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Naufrage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Neige');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Nombres / Chiffres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Oiseaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Ombres');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Ours');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pacifique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pandas');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Papillons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Peinture');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pêche');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Photographie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pierres précieuses');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pingouins');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Piraterie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pirates');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Piscine');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pizzas');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Plage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Poésie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Poissons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Poker');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Politique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pompiers');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Port');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Potion magique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Poules');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Poulpes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Pôle Nord');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Préhistoire');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Prison');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Proche-Orient');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Recette');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Recherche');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Renaissance');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Renards');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Repas');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Requins');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Rêves');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Rhinocéros');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Rivière');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Robots');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Ruée vers l''or');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Saisons');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Samourai');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Science-Fiction');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Senji');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Serpents');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Singes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sixties');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Soleil');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Souris');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sous-marin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport Arts martiaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport Automobile');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport Cyclisme');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport Football');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport Hippique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport Nautique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Suisse');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Taupes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Temps');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Théâtre');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Tortues');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Tourisme');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Tournoi');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Train');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Transport aérien');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Transport automobile');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Transport ferroviaire');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Transport marin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Transport spatial');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Travail / Bureau');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Urbanisme / Construction');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vacances');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vaches');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vaisseau spatial');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vautours');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vers');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vélo');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vêtements');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vikings');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Ville');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vin');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Vocabulaire');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Voitures');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Volcan');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Voyage');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Voyage dans le temps');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Voyance / Divination');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Western','Les jeux avec des beaux chapeaux');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Zombies');